export type OnlineReservationType = {
  room_id: number,
  date_from: string,
  date_to: string,
  age_group_number_1: number,
  age_group_number_2: number,
  age_group_number_3: number,
  age_group_number_4: number,
  age_group_number_5: number,
  name: string,
  email: string,
  phone: string,
  notes: string,
  is_invoice?: boolean,
  company_name?: string,
  nip?: string,
  street?: string,
  house_number?: string,
  apartment_number?: string,
  postal_code?: string,
  city?: string,
  payment_method: string,
  service_numbers: any,
  has_discount?: boolean,
  country?: string,
  vehicle_type?: string,
  vehicle_plate?: string,
}
